spring:
  config:
    activate:
      on-profile: local

  datasource:
    # MYSQL
    url: jdbc:mysql://localhost:3306/repellerDB
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:

  # H2DB
  #    url: jdbc:h2:tcp://localhost/~/my-db-test
  #    username: sa
  #    password:
  #    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: never